<div class="shop-intro">
	<h1>商铺介绍</h1>
	<div><?=$this->shop["Description"]?></div>
	<table>
		<tr>
			<td style="width:250px;"><label>商家名称：</label><?=$this->shop["Name"]?></td>
			<td><label>企业类型：</label><?=$this->shop["Type"]?></td>
		</tr>
		<tr>
			<td><label>经营品牌：</label><?=$this->shop["Brands"]?></td>
			<td><label>网　　址：</label><?=$this->shop["Url"]?></td>
		</tr>
		<tr>
			<td><label>联   系   人：</label><?=$this->shop["Contact"]?></td>
			<td><label>联系电话：</label><?=$this->shop["MobilePhone"].','.$this->shop["TelPhone"]?></td>
		</tr>
		<tr>
			<td><label>主营行业：</label><?=$this->shop["Industry"]?></td>
			<td><label>主营产品：</label><?=$this->shop["Products"]?></td>
		</tr>
	</table>
</div>
