<?= $this->partial('news/_left.phtml') ?>
<div class="arts box">
	<?foreach ($this->news as $news) {?>
		<div class="art">
			<h3 class="art-title"><a target="_blank" href="/news/<?=$news['Id']?>.html"><?=$news['Title']?></a></h3>
			<div class="art-meta">
				<span>发表于：<?=date('Y-m-d', strtotime($news['CreatedAt']))?></span>
				<span>浏览数：<?=$news['Views']?></span>
			</div>
			<div class="art-summary">
				<div class="art-pic">
					<a href="/news/<?=$news['Id']?>.html" title="<?=$news['Title']?>">
						<img width="150" src="<?=$news['PicUrl']?>" alt="<?=$news['Title']?>"/>
					</a>
				</div>
				<div class="art-summary-context">
					<?=$news["Summary"]?>
				</div>
			</div>
			<div class="art-readmore">
				<div class="readmore">
					<a href="/news/<?=$news['Id']?>.html">继续阅读</a>
				</div>
			</div>
			<hr/>
		</div>
	<?}?>
</div>