<?= $this->partial('article/_left.phtml', array('hots'=>$this->hots)) ?>
<div class="arts box">
	<?foreach ($this->articles as $article) {?>
		<div class="art">
			<h3 class="art-title"><a target="_blank" href="/article/<?=$article['Id']?>.html"><?=$article['Title']?></a></h3>
			<div class="art-meta">
				<span>发表于：<?=date('Y-m-d', strtotime($article['CreatedAt']))?></span>
				<span>浏览数：<?=$article['Views']?></span>
			</div>
			<div class="art-summary">
				<div class="art-pic">
					<a href="/article/<?=$article['Id']?>.html" title="<?=$article['Title']?>">
						<img width="150" src="<?=$article['PicUrl']?>" alt="<?=$article['Title']?>"/>
					</a>
				</div>
				<div class="art-summary-context">
					<?=$article["Summary"]?>
				</div>
			</div>
			<div class="art-readmore">
				<div class="readmore">
					<a href="/article/<?=$article['Id']?>.html">继续阅读</a>
				</div>
			</div>
			<hr/>
		</div>
	<?}?>
</div>