<div class="shop-header">
	<div class="shop-banner" style="background:url(<?=$this->shop["Banner"]?>)">
	</div>
	<ul class="nav shop-nav">
	    <li class="<?=($this->actionName=='index'?'selected':'')?>">
	    	<a href="/shop/<?=$this->shop["Id"]?>.html">商铺首页</a>
	    </li>
	    <li class="<?=($this->actionName=='intro'?'selected':'')?>">
	    	<a href="/shop/<?=$this->shop["Id"]?>/intro.html">商铺介绍</a>
	    </li>
	    <li class="<?=($this->actionName=='products'?'selected':'')?>">
	    	<a href="/shop/<?=$this->shop["Id"]?>/products.html">商品列表</a>
	    </li>
	</ul>
	<div class="box-shadow"></div>
</div>
