<div class="shop-left-top">商家信息</div>
<div class="shop-left">
	<div class="shop-brand">
		<img src="<?=$this->shop["Logo"]?>"/>
	</div>
	<hr size=1 class="dot-line" style="width:150px;"> 
	<div class="shop-info">
		<h1><?=$this->shop["Name"]?></h1>
		<table>
			<tr>
				<td style="width:40px;">手机：</td>
				<td><?=$this->shop["MobilePhone"]?></td>
			</tr>
			<tr>
				<td>电话：</td>
				<td><?=$this->shop["TelPhone"]?></td>
			</tr>
			<tr>
				<td>地址：</td>
				<td><?=$this->shop["Address"]?></td>
			</tr>
			<tr>
				<td>公交：</td>
				<td><?=$this->shop["Bus"]?></td>
			</tr>
			<tr>
				<td>客服：</td>
				<td></td>
			</tr>
		</table>
	</div>
	<hr size=1 class="dot-line" style="width:150px;"> 
	<div class="shop-info">
		<table>
			<tr>
				<td>店铺人气：</td>
				<td><?=$this->shop["Views"]?></td>
			</tr>
			<tr>
				<td>入驻时间：</td>
				<td><?=$this->shop["CreatedAt"]?></td>
			</tr>
		</table>
	</div>
	<hr size=1 class="dot-line" style="width:150px;"> 
	<div class="shop-info">
		<ul>
			<li><a href="#">正品保障</a></li>
			<li><a href="#">提供发票</a></li>
			<li id="J_7day" class="last"><a href="#">七天退换</a></li>
			</ul>
	</div>
</div>