<div style="background-color:#F2F2F2;height:25px;padding-left:10px;">商家信息</div>
<div class="shop-left" style="padding:10px;">
	<div class="shop-brand" style="margin:10px 0px 10px 0px;">
		<img src="http://tenpp.com/JJ/JJCS_1_1_8.gif"?>
	</div>
	<hr size=1 style="color: blue;border-style:dotted;width:150;margin:auto 0;"> 
	<div class="shop-info" style="margin:10px 0px 10px 0px;">
		<h1 style="margin:auto 0;">江阴家居乐</h1>
		<table>
			<tr>
				<td style="width:40px;">电话：</td>
				<td>0510-6888888<br/>18651005969</td>
			</tr>
			<tr>
				<td>地址：</td>
				<td>果园路28号新生活家居广场3楼A区15号</td>
			</tr>
			<tr>
				<td>公交：</td>
				<td>2路、1路</td>
			</tr>
			<tr>
				<td>客服：</td>
				<td></td>
			</tr>
		</table>
	</div>
	<hr size=1 style="color: blue;border-style:dotted;width:150;margin:auto 0;"> 
	<div style="margin:10px 0px 10px 0px;">
		<table>
			<tr>
				<td>店铺人气：</td>
				<td>980</td>
			</tr>
			<tr>
				<td>入驻时间：</td>
				<td>2012年9月10日</td>
			</tr>
		</table>
	</div>
	<hr size=1 style="color: blue;border-style:dotted;width:150;margin:auto 0;"> 
	<div style="margin:10px 0px 10px 0px;">
		<ul>
			<li><a href="#">正品保障</a></li>
			<li><a href="#">提供发票</a></li>
			<li id="J_7day" class="last"><a href="#">七天退换</a></li>
			</ul>
	</div>
</div>