<div class="shop-left-top">商家信息</div>
<div class="shop-left">
	<div class="shop-brand">
		<img width="180" src="<?=$this->shop["Logo"]?>"/>
	</div>
	<hr size=1 class="dot-line" style="width:150px;"> 
	<div class="shop-info">
		<h1><?=$this->shop["Name"]?></h1>
		<table>
			<tr>
				<td style="width:45px;"><label>手 机：</label></td>
				<td><?=$this->shop["MobilePhone"]?></td>
			</tr>
			<tr>
				<td><label>电 话：</label></td>
				<td><?=$this->shop["TelPhone"]?></td>
			</tr>
			<tr>
				<td><label>地 址：</label></td>
				<td><?=$this->shop["Address"]?></td>
			</tr>
			<tr>
				<td><label>公 交：</label></td>
				<td><?=$this->shop["Bus"]?></td>
			</tr>
			<tr>
				<td><label>客 服：</label></td>
				<td></td>
			</tr>
		</table>
	</div>
	<hr size=1 class="dot-line" style="width:150px;"> 
	<div class="shop-info">
		<table>
			<tr>
				<td style="width:60px;">店铺人气：</td>
				<td><?=$this->shop["Views"]+1?></td>
			</tr>
			<tr>
				<td>入驻时间：</td>
				<td><?=date("Y年m月d日",strtotime($this->shop["CreatedAt"]))?></td>
			</tr>
		</table>
	</div>
	<hr size=1 class="dot-line" style="width:150px;"> 
	<div class="shop-info">
		<ul class="nav badges">
			<? foreach ($this->badges as $badge) {?>
				<li><a href="#" title="<?=$badge['Name']?>"><img src="<?=$badge['PicUrl']?>" alt="<?=$badge['Name']?>"/></a></li>
			<?}?>
		</ul>
	</div>
</div>