<ul class="products nav">
	<li>
		<div calss="pd-img">
			<div>
				<a href="#"><img src="http://img01.taobaocdn.com/bao/uploaded/i1/T1CdBuXldyXXXvfCQ6_063041.jpg_b.jpg"></a>
			</div>
			<div>
				<a href="#">铁艺水晶蜡烛吊灯 卧室灯具 餐吊灯SDT-6D7935有现货</a>
			</div>
		</div>
		<div class="pd-desc">
			<span>价格：</span><span class="price">面议</span>
		</div>
	</li>

	<li>
		<div class="pd-img">
			<div>
				<a href="#"><img src="http://img01.taobaocdn.com/bao/uploaded/i1/T1CdBuXldyXXXvfCQ6_063041.jpg_b.jpg"></a>
			</div>
			<div>
				<a href="#">铁艺水晶蜡烛吊灯 卧室灯具 餐吊灯SDT-6D7935有现货</a>
			</div>
		</div>
		<div class="pd-desc">
			<span>价格：</span><span class="price">88.00元</span>
		</div>
	</li>

	<li>
		<div class="pd-img">
			<div>
				<a href="#"><img src="http://img01.taobaocdn.com/bao/uploaded/i1/T1CdBuXldyXXXvfCQ6_063041.jpg_b.jpg"></a>
			</div>
			<div>
				<a href="#">铁艺水晶蜡烛吊灯 卧室灯具</a>
			</div>
		</div>
		<div class="pd-desc">
			<span>价格：</span><span class="price">70.00元</span>
		</div>
	</li>

	<li>
		<div class="pd-img">
			<div>
				<a href="#"><img src="http://img01.taobaocdn.com/bao/uploaded/i1/T1CdBuXldyXXXvfCQ6_063041.jpg_b.jpg"></a>
			</div>
			<div>
				<a href="#">铁艺水晶蜡烛吊灯 卧室灯具 餐吊灯SDT-6D7935有现货</a>
			</div>
		</div>
		<div class="pd-desc">
			<span>价格：</span><span class="price">70.00元</span>
		</div>
	</li>
</ul>