<form enctype="multipart/form-data" action="" method="post">   
	<table>
		<tr>
			<td>选择文件</td>
			<td><input name="uploadFile" type="file"></td>
		</tr>
		<tr>
			<td>目录</td>
			<td>
				<select name="channel">
					<option value="sp">店铺</option>
					<option value="pd">商品</option>
					<option value="at">文章</option>
					<option value="ad">广告</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>文件名</td>
			<td><input name="fileName" type="text"></td>
		</tr>
		<tr>
			<td>后缀</td>
			<td>
				<select name="suffix">
					<option value="">无后缀</option>
					<option value="_40x40">40x40</option>
					<option value="_310x310">310x310</option>
				</select>
			</td>
		</tr>
		<tr>
			<td colsolespan="2"><input type="submit" value="上传文件"></td>
		</tr>
	</table>	   
</form>  