 <script type="text/javascript" src="/js/jquery.slidy.js"></script>
 <div class="container ad">
    <div class="ad-left">
        <div class="ad-top">
            <a href="#" target="_blank" title="恭贺红美商城正式上线">
                <img title="恭贺红美商城正式上线" src="http://img02.homemall.com.cn/cms/image/20120905/20120905101924_49970.jpg" width="728" height="300">
            </a>
            <a href="#" title="欧式床2880包物流" target="_blank" style="display:none">
                <img title="欧式床2880包物流" src="http://image.meilele.com/images/201209/1346720464661689474.jpg" width="728" height="300">
            </a>
            <a href="#" title="全块26元起疯抢" target="_blank" style="display:none">
                <img title="全块26元起疯抢" src="http://image.meilele.com/images/201208/1346370093076409610.jpg" width="728" height="300">
            </a>
            <a href="#" title="劲爆特价直击价格底线" target="_blank" style="display:none">
                <img title="劲爆特价直击价格底线" src="http://img01.homemall.com.cn/cms/image/20120904/20120904195129_95909.jpg" width="728" height="300">
            </a>
        </div>
    </div>
    <div class="ad-right">
        <div class="min-bar">
            <ul class="min-bar-toggle">
                <li class="selected">新闻公告</li>
                <li>学装修</li>
            </ul>
            <div class="min-bar-content">
                <ul class="nav-v">
                    <li><a href=""><span>[公告]</span>新生活家居广场9.8六周年庆典</a></li>
                    <li><a href=""><span>[公告]</span>新生活家居广场9.8六周年庆典</a></li>
                    <li><a href=""><span>[公告]</span>新生活家居广场9.8六周年庆典</a></li>
                    <li><a href=""><span>[公告]</span>新生活家居广场9.8六周年庆典</a></li>
                    <li><a href=""><span>[公告]</span>新生活家居广场9.8六周年庆典</a></li>
                    <li><a href=""><span>[公告]</span>新生活家居广场9.8六周年庆典</a></li>                    
                </ul>    
            </div>
            <div>
                <ul>
                    <li></li>
                </ul>
            </div>
        </div>
        <div class="min-bar">
            <div class="min-bar-title">
                <span>热销品牌</span>
            </div>
            <ul class="hot-brand">
                <li>
                    <a target="_blank" href="#"><img src="http://app.jysq.net/attach/image/2011/0720/02-01-12-1011457716.jpg" width="200" height="54" alt=""></a>
                </li>
                <li>
                    <a target="_blank" href="#"><img src="http://app.jysq.net/attach/image/2011/0720/02-01-18-397597658.jpg" width="200" height="54" alt=""></a>
                </li>
            </ul>
        </div>
    </div>
</div>