 <script type="text/javascript" src="/js/jquery.slidy.js"></script>
 <div class="container ad">
    <div class="ad-left">
        <div class="ad-top">
            <a href="http://www.ecejia.com/shop/1006.html" target="_blank" title="飞利浦LED热卖">
                <img title="飞利浦LED热卖" src="http://www.ecejia.com/upload/ad/201209/09091002.jpg" width="728" height="300">
            </a>
            <a href="http://q.mmall.com/cate-all.html" target="_blank" title="恭贺红美商城正式上线">
                <img title="恭贺红美商城正式上线" src="http://img02.homemall.com.cn/cms/image/20120905/20120905101924_49970.jpg" width="728" height="300">
            </a>
            <a href="http://www.ecejia.com/shop/1004.html" title="江阴鹰卫浴" target="_blank">
                <img title="江阴鹰卫浴" src="http://www.ecejia.com/upload/ad/201209/09092822.jpg" width="728" height="300">
            </a>
            <a href="http://www.ecejia.com/shop/1003.html" title="江阴利豪沙发" target="_blank" style="display:none">
                <img title="江阴利豪沙发" src="http://www.ecejia.com/upload/ad/201209/06100729.png" width="728" height="300">
            </a>
        </div>
    </div>
    <div class="ad-right">
        <div class="min-bar">
            <ul class="min-bar-toggle">
                <li class="selected">新闻公告</li>
                <li>装修宝典</li>
            </ul>
            <div class="min-bar-content">
                <ul class="nav-v">
                    <li><a target="blank" href="/news/3.html"><span>[新闻]</span>发改委调查电商价格战</a></li>
                    <li><a target="blank" href="#"><span>[公告]</span>E城E家9.9上线，商家可免费入驻</a></li>                   
                </ul> 
                <ul class="nav-v hide">
                    <li><a target="blank" href="zhuangxiu/1.html"><span>[装修]</span>秋季干燥 装修需注意五点细节</a></li>
                    <li><a target="blank" href="zhuangxiu/2.html"><span>[装修]</span>装修风水宝典</a></li>  
                </ul>
            </div>
        </div>
        <div class="min-bar">
            <div class="min-bar-title">
                <span>热销品牌</span>
            </div>
            <ul class="hot-brand">
                <li>
                    <a target="_blank" href="http://www.ecejia.com/shop/1003.html" title="江阴利豪沙发"><img src="http://www.ecejia.com/upload/sp/201209/06013407.png" width="200" height="54" alt="江阴利豪沙发"></a>
                </li>
                <li>
                    <a target="_blank" href="http://www.ecejia.com/shop/1002.html" title="诺维家衣柜"><img src="http://www.ecejia.com/upload/sp/201209/06111047.png" width="200" height="54" alt="诺维家衣柜"></a>
                </li>
            </ul>
        </div>
    </div>
</div>