 <script type="text/javascript" src="/js/jquery.slidy.js"></script>
 <div class="container ad">
            <div class="ad-left">
                <div class="ad-top">
                    <a href="#" target="_blank">
                        <img title="Kids开学季秋装新登场！" src="http://img.m18.com/web/pic/hp/1208/0821/banner5a.jpg" width="728" height="337">
                    </a>
                    <a href="#" title="Amii百搭款T恤￥99/2件" target="_blank" style="display:none">
                        <img title="Amii百搭款T恤￥99/2件" src="http://img.m18.com/web/pic/hp/1208/0824/banner1bb.jpg" width="728" height="337">
                    </a>
                    <a href="#" title="Idole秋装4.1折强势登陆" target="_blank" style="display:none">
                        <img title="Idole秋装4.1折强势登陆" src="http://img.m18.com/web/pic/hp/1208/0824/bannera.jpg" width="728" height="337">
                    </a>
                    <a href="#" title="College优雅连衣裙￥75" target="_blank" style="display:none">
                        <img title="College优雅连衣裙￥75" src="http://img.m18.com/web/pic/hp/1208/0823/banner3.jpg" width="728" height="337">
                    </a>
                </div>
            </div>
            <div class="ad-right">
                <div class="min-bar">
                    <ul class="min-bar-toggle">
                        <li class="selected">新闻公告</li>
                        <li>学装修</li>
                    </ul>
                    <div class="min-bar-content">
                        <ul class="nav-v">
                            <li>学装修学装修学装修学装修学装修学装修</li>
                            <li>aaaa</li>
                            <li>aaaa</li>
                            <li>aaaa</li>
                            <li>bbbbbb</li>
                        </ul>    
                    </div>
                    <div>
                        <ul>
                            <li></li>
                        </ul>
                    </div>
                </div>
                <div class="min-bar">
                    <div class="min-bar-title">
                        <span>热销品牌</span>
                    </div>
                    <ul class="hot-brand">
                        <li><a target="_blank" href="#"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="100" height="58"></a></li>
                        <li><a target="_blank" href="#"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="100" height="58"></a></li>
                        <li><a target="_blank" href="#"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="100" height="58"></a></li>
                        <li><a target="_blank" href="#"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="100" height="58"></a></li>
                        <li><a target="_blank" href="#"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="100" height="58"></a></li>
                        <li><a target="_blank" href="#"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="100" height="58"></a></li>
                    </ul>
                </div>
            </div>
        </div>