<div class="nav-bar-top">
    <ul class="nav container">
        <li class="active">首页</li>
        <li>
            <a href="#">家居饰品</a>
            <div class="nav-sub-box">
                <div class="nav-sub-detail-box">
                    <dl class="nav-sub-detail-item">
                        <dt>工艺饰品</dt>
                        <dd><a target="_blank" href="#" class="h">创意饰品</a></dd>
                        <dd><a target="_blank" href="#">创意饰品</a></dd>
                        <dd><a target="_blank" href="#" class="h">挂历/台历</a></dd>
                        <dd><a target="_blank" href="#">工艺船</a></dd>
                        <dd><a target="_blank" href="#">风铃</a></dd>
                        <dd><a target="_blank" href="#">挂饰/壁饰</a></dd>
                        <dd><a target="_blank" href="#">装饰架/隔板</a></dd>
                        <dd><a target="_blank" href="#">装饰挂钩</a></dd>
                        <dd><a target="_blank" href="#">挂牌/门牌</a></dd>
                    </dl>
                    <dl class="nav-sub-detail-item">
                        <dt>家居摆件</dt>
                        <dd><a target="_blank" href="#">摆件</a></dd>
                        <dd><a target="_blank" href="#">雕刻</a></dd>
                        <dd><a target="_blank" href="#">烛台</a></dd>
                        <dd><a target="_blank" href="#">饰品盒</a></dd>
                        <dd><a target="_blank" href="#">挂钟闹钟</a></dd>
                    </dl>
                </div>
                <div class="nav-sub-detail-box">
                    <dl class="nav-sub-detail-item">
                        <dt>家居贴饰</dt>
                        <dd><a target="_blank" href="#">墙贴</a></dd>
                        <dd><a target="_blank" href="#">玻璃帖</a></dd>
                        <dd><a target="_blank" href="#">开关帖</a></dd>
                        <dd><a target="_blank" href="#">冰箱帖</a></dd>
                    </dl>
                    <dl class="nav-sub-detail-item">
                        <dt>花瓶/花卉</dt>
                        <dd><a target="_blank" href="#">花瓶</a></dd>
                        <dd><a target="_blank" href="#">仿真花</a></dd>
                        <dd><a target="_blank" href="#">果盘</a></dd>
                        <dd><a target="_blank" href="#">装饰器皿</a></dd>
                        <dd><a target="_blank" href="#">仿真饰品</a></dd>
                    </dl>
                </div>
            </div>
        </li>
        <li>
            <a href="#">住宅家具</a>
            <div class="nav-sub-box">
                <div class="nav-sub-detail-box">
                    aaaaaaaaaaaaaaaaaaaaa
                </div>
            </div>
        </li>
        <li><a href="#">家纺布艺</a></li>
        <li><a href="#">家装主材</a></li>
        <li><a href="#">五金电工</a></li>
        <li><a href="#">学装修</a></li>
    </ul>
</div>
