<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- saved from url=(0025)http://m.163.com/android/ -->
<html xmlns="http://www.w3.org/1999/xhtml" class="yui3-js-enabled">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Keywords" content="">
    <meta name="Description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
    <link rel="shortcut icon" href="/images/favicon.ico">
    <!-- <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css"> -->
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <script type="text/javascript" src="/js/jquery-1.8.0.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/main.js" charset="utf-8"></script>
    <title>E家</title>
</head>
<body>
    <div class="wrapper">
        <div class="header">
            aaaaaaaaaa
        </div>
        <div class="nav-bar-top">
                <ul class="nav container">
                    <li class="active">首页</li>
                    <li><a href="#">家居</a></li>
                    <li><a href="#">家纺</a></li>
                    <li><a href="#">照明</a></li>
                    <li><a href="#">厨房</a></li>
                    <li><a href="#">卫浴</a></li>
                    <li><a href="#">建材</a></li>
                    <li><a href="#">学装修</a></li>
                </ul>
        </div>
        <div class="container ad">
            <div class="ad-l">
                <div class="ad-t">
                    <a href="http://static.m18.com/lp/120820c_Kids.shtml#rel=MDT010E" title="Kids开学季秋装新登场！" target="_blank" name="__MDT0010E"><img alt="Kids开学季秋装新登场！" src="http://img.m18.com/web/pic/hp/1208/0821/banner5a.jpg" width="728" height="337"></a>
                </div>
                    <ul class="nav ad-b">
                        <li><a target="_blank" href="#">Amii百搭款T恤￥99/2件</a></li>
                        <li><a target="_blank" href="#">Idole秋装4.1折强势登陆</a></li>
                        <li><a target="_blank" href="#">College优雅连衣裙￥75</a></li>
                        <li><a target="_blank" href="#">Mind&Style情侣装￥139</a></li>
                        <li><a target="_blank" href="#">Kids开学季秋装新登场！</a></li>
                    </ul>
            </div>
            <div class="ad-r">
                <div class="min-bar">
                    <div class="toggle-bar">
                        学装修
                    </div>
                    <ul class="nav-v">
                        <li>aaaa</li>
                        <li>aaaa</li>
                        <li>aaaa</li>
                        <li>aaaa</li>
                    </ul>   
                </div>
                <div class="min-bar">
                    <div class="toggle-bar">
                        热销品牌
                    </div>
                    <ul class="nav-a">
                        <li><a target="_blank" href="http://static.m18.com/brand/euromoda.shtml#rel=mpp02E"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="80" height="58"></a></li>
                        <li><a target="_blank" href="http://static.m18.com/brand/euromoda.shtml#rel=mpp02E"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="80" height="58"></a></li>
                        <li><a target="_blank" href="http://static.m18.com/brand/euromoda.shtml#rel=mpp02E"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="80" height="58"></a></li>
                        <li><a target="_blank" href="http://static.m18.com/brand/euromoda.shtml#rel=mpp02E"><img alt="Euromoda" src="http://img.m18.com/web/pic/hp/1111/1118/110411_Euromoda_110x58.jpg" width="80" height="58"></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</body>
</head>