<div class="box category">
	<div class="cate-title">
		<?= $this->currentClassName ?>
	</div>
	<div class="cate-list">
		<? foreach ($this->categories as $category) {
			if($category["ClassId2"] == 0 || $category["ClassId2"] == NULL){?>
			<div class="cate-item">
				<span class="cate-name"><?=$category["Name"]?></span>
				<hr size=1 class="line" />
				<ul class="nav">
					<? foreach ($this->categories as $subCate) {
						if($subCate["ClassId2"] == $category["Id"]){?>
						<li>
							<a target="_blank" href="/list/<?=$subCate["Id"]?>.html"><?=$subCate["Name"]?></a>
						</li>
					<?}}?>
				</ul>
			</div>
		<?}}?>
	</div>
</div>