<style type="text/css">
.box{
	border:1px solid #DDDDDD;
	border-radius:0 0 3px 3px;

	filter: progid:DXImageTransform.Microsoft.Shadow(color='#BBB3C1', Direction=145, Strength=3);  
	-webkit-box-shadow: 2px 2px 3px #BBB3C1; 
	-moz-box-shadow: 2px 2px 3px #BBB3C1;
	box-shadow: 2px 2px 3px #BBB3C1;
}
.category
{
	width:200px;
	margin: 10px;
	padding-bottom:20px;
	background-color:#FAFAFA;
	float: left;
}
.cate-title{
	width:100%;
	height: 30px;
	background: url(/img/cate-bg.jpg);
	text-align: center;
	line-height: 28px;
	color: white;
	font-size: 14px;
	font-weight: bold;
}
.cate-list{
	padding:0px 10px 0px 10px;
}
.cate-item{
	clear:both;
	padding-top: 10px;
}
.cate-item li{
	width:70px;
	text-align: left;
	padding: 0 6px 0 6px;
}
.cate-item li:hover{
	background-color: #FFE1E1;
}
.cate-name{
	padding-left: 5px;
	font-size: 14px;
	font-weight: bold;
}
.line{
	width:100%;
	color: red;
}
</style>

<div class="box category">
	<div class="cate-title">家居饰品</div>
	<div class="cate-list">
		<? foreach ($this->categories as $category) {
			if($category["ClassId2"] == 0 || $category["ClassId2"] == NULL){?>
			<div class="cate-item">
				<span class="cate-name"><?=$category["Name"]?></span>
				<hr size=1 class="line" />
				<ul class="nav">
					<? foreach ($this->categories as $subCate) {
						if($subCate["ClassId2"] == $category["Id"]){?>
						<li><a href="#"><?=$subCate["Name"]?></a></li>
					<?}}?>
				</ul>
			</div>
		<?}}?>
	</div>
</div>