<div class="floor">
    <div class="floor-top">
        <h2 class="floor-title"><span class="floor-name">2F</span>家纺</h2>
        <ul class="floor-nav">
            <li>套装</li>
            <li>被子/床褥</li>
            <li>枕头</li>
            <li>毛巾/浴巾</li>
            <li>窗帘</li>
            <li>毛毯</li>
        </ul>
    </div>
    <div class="floor-middle">
        <ul class="floor-left floor-left-2">
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
        </ul>
        <div class="floor-right">






                            <a class="j_MaskItem floor-maskItem hover" target="_blank" href="http://www.tmall.com/go/act/sale/dongqingxiyun.php?spm=3.1000473.246617.33" style="top:0px;left:0px;" data-spm-anchor-id="3.1000473.246617.33">
                    <img width="195" height="150" src="http://img04.taobaocdn.com/imgextra/i4/90919986/T2TFuBXjhbXXXXXXXX_!!90919986.jpg" alt="东情西韵">
                <div style="top: 0px; left: 0px; width: 195px; height: 150px; position: absolute; background-color: rgb(0, 0, 0); opacity: 0; cursor: pointer; background-position: initial initial; background-repeat: initial initial; " class="maskLayer"></div></a>
                            <a class="j_MaskItem floor-maskItem" target="_blank" href="http://skii.tmall.com/?spm=3.1000473.246617.34" style="top:0px;left:195px;" data-spm-anchor-id="3.1000473.246617.34">
                    <img width="390" height="150" src="http://img02.taobaocdn.com/tps/i2/T1.ufHXbVdXXcaZvZe-390-150.png" alt="skii">
                <div style="top: 0px; left: 0px; width: 390px; height: 150px; position: absolute; background-color: rgb(0, 0, 0); opacity: 0.3; cursor: pointer; background-position: initial initial; background-repeat: initial initial; " class="maskLayer"></div></a>
                            <a class="j_MaskItem floor-maskItem" target="_blank" href="http://mei.tmall.com/mancare.htm?spm=3.1000473.246617.35" style="top:150px;left:0px;" data-spm-anchor-id="3.1000473.246617.35">
                    <img width="195" height="150" src="http://img01.taobaocdn.com/tps/i1/T1.3PBXidmXXc2tkZK-195-150.png" alt="美容馆男士护肤">
                <div style="top: 0px; left: 0px; width: 195px; height: 150px; position: absolute; background-color: rgb(0, 0, 0); opacity: 0.3; cursor: pointer; background-position: initial initial; background-repeat: initial initial; " class="maskLayer"></div></a>
                            <a class="j_MaskItem floor-maskItem" target="_blank" href="http://list.tmall.com/search_product.htm?spm=3.1000473.246617.36&amp;q=%CC%D7%D7%B0&amp;area_code=330100&amp;sort=s&amp;style=g&amp;vmarket=0&amp;active=1&amp;cat=50026461" style="top:0px;left:585px;" data-spm-anchor-id="3.1000473.246617.36">
                    <img width="195" height="300" src="http://img01.taobaocdn.com/tps/i1/T1ZO2GXhBhXXXoDBZK-195-300.png" alt="首饰套件">
                <div style="top: 0px; left: 0px; width: 195px; height: 300px; position: absolute; background-color: rgb(0, 0, 0); opacity: 0.3; cursor: pointer; background-position: initial initial; background-repeat: initial initial; " class="maskLayer"></div></a>
                            <a class="j_MaskItem floor-maskItem" target="_blank" href="http://list.tmall.com/search_product.htm?spm=3.1000473.246617.37&amp;active=1&amp;from=sn_1_prop&amp;area_code=330100&amp;search_condition=16&amp;vmarket=0&amp;style=g&amp;sort=s&amp;start_price=100&amp;prop=34343:112571&amp;n=60&amp;s=0&amp;cat=50108176#J_crumbs" style="top:150px;left:195px;" data-spm-anchor-id="3.1000473.246617.37">
                    <img width="195" height="150" src="http://img03.taobaocdn.com/tps/i3/T1VPjDXXFfXXc2tkZK-195-150.png" alt="腕表">
                <div style="top: 0px; left: 0px; width: 195px; height: 150px; position: absolute; background-color: rgb(0, 0, 0); opacity: 0.3; cursor: pointer; background-position: initial initial; background-repeat: initial initial; " class="maskLayer"></div></a>
                            <a class="j_MaskItem floor-maskItem" target="_blank" href="http://list.tmall.com/search_product.htm?spm=3.1000473.246617.38&amp;active=1&amp;from=sn_1_cat&amp;area_code=330100&amp;navlog=5&amp;nav=spu-cat&amp;search_condition=16&amp;vmarket=0&amp;style=g&amp;sort=s&amp;n=48&amp;s=0&amp;cat=50026478&amp;is=cate#J_crumbs" style="top:150px;left:390px;" data-spm-anchor-id="3.1000473.246617.38">
                    <img width="195" height="150" src="http://img02.taobaocdn.com/tps/i2/T1VZHDXd4iXXc2tkZK-195-150.png" alt="铂金">
                <div style="top: 0px; left: 0px; width: 195px; height: 150px; position: absolute; background-color: rgb(0, 0, 0); opacity: 0.3; cursor: pointer; background-position: initial initial; background-repeat: initial initial; " class="maskLayer"></div></a>

        </div>
    </div>
    <div class="floor-bottom"></div>
</div>