<div class="floor">
    <div class="floor-top">
        <div class="floor-top-bar">
            <a class="floor-title-4" href="/channel/jiazhuang.html"></a>
        </div>
    </div>
    <ul class="hot-categorys f4">
        <li><div><a href="/list/412.html">淋浴花洒</a></div><div><a href="/list/414.html">浴缸</a></div></li>
        <li><div><a href="/list/416.html">沐浴房</a></div><div><a href="/list/419.html">台上盆</a></div></li>
        <li><div><a href="/lit/421.html">顶灯</a></div><div><a href="/list/422.html">壁灯</a></div></li>
        <li><div><a href="/list/423.html">落地灯</a></div><div><a href="/list/426.html">新奇特灯具</a></div></li>
        <li><div><a href="/list/433.html">实木地板</a></div><div><a href="/list/434.html">实木复合地板</a></div></li>
        <li><div><a href="/list/436.html">马赛克</a></div><div><a href="/list/441.html">电热水器</a></div></li>
        <li><div><a href="/list/443.html">太阳能热水器</a></div><div><a href="/list/444.html">集成吊顶</a></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
    </ul>
    <div class="items floor-middle-r">
        <a class="item" target="_blank" width="195" height="150" href="http://www.ecejia.com/product/419-0001.html" style="top:0px;left:0px;">
            <img width="195" height="150" src="http://img03.taobaocdn.com/bao/uploaded/i3/T1SfdDXh0mXXXA.mA._083413.jpg_310x310.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/shop/1005.html" style="top:0px;left:195px;">
            <img width="390" height="150" src="http://www.ecejia.com/upload/ad/201209/12024442.jpg" alt="skii">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/41A-0001.html" style="top:150px;left:0px;">
            <img width="195" height="150" src="http://img02.taobaocdn.com/bao/uploaded/i2/T1aI5EXitvXXXEcK79_103256.jpg_310x310.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/shop/1005.html" style="top:0px;left:585px;">
            <img width="185" height="300" src="http://www.ecejia.com/upload/ad/201209/12025026.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/414-0001.html" style="top:150px;left:195px;" >
            <img width="195" height="150" src="http://img02.taobaocdn.com/bao/uploaded/i2/T1NMBAXfpFXXbqRFTb_122707.jpg_310x310.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/41B-0001.html" style="top:150px;left:390px;">
            <img width="195" height="150" src="http://img04.taobaocdn.com/bao/uploaded/i4/T1JIxIXgpvXXcBpkjX_085744.jpg_310x310.jpg" alt="">
        </a>
    </div>
    <div class="floor-bottom"></div>
</div>