<div class="floor">
    <div class="floor-top">
        <div class="floor-top-bar">
            <a class="floor-title-1" href="/channel/jiaju.html"></a>
        </div>
    </div>
    <ul class="hot-categorys">
        <li><div><a target="_blank" href="/list/111.html">实木床</a></div><div><a target="_blank" href="/list/112.html">布艺床</a></div></li>
        <li><div><a target="_blank" href="/list/113.html">沙发床</a></div><div><a target="_blank" href="/list/114.html">儿童床</a></div></li>
        <li><div><a target="_blank" href="/list/121.html">布沙发</a></div><div><a target="_blank" href="/list/122.html">皮沙发</a></div></li>
        <li><div><a target="_blank" href="/list/124.html">实木沙发</a></div><div><a target="_blank" href="/list/125.html">懒人沙发</a></div></li>
        <li><div><a target="_blank" href="/list/126.html">贵妃椅</a></div><div><a target="_blank" href="/list/127.html">沙发床</a></div></li>
        <li><div><a target="_blank" href="/list/131.html">衣柜</a></div><div><a target="_blank" href="/list/133.html">电视柜</a></div></li>
        <li><div><a target="_blank" href="/list/134.html">床头柜</a></div><div><a target="_blank" href="/list/135.html">书柜</a></div></li>
        <li><div><a target="_blank" href="/list/155.html">书架</a></div><div><a target="_blank" href="/list/156.html">茶机</a></div></li>
        <li><div><a target="_blank" href="/list/158.html">书桌</a></div><div><a target="_blank" href="/list/157.html">餐桌</a></div></li>
        <li><div></div><div></div></li>
    </ul>
    <div class="items floor-middle-r">
        <a class="item" target="_blank" href="http://www.ecejia.com/shop/1008.html" >
            <img style="width:390px;height:300px;" src="http://www.ecejia.com/upload/ad/201209/11095401.jpg">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/121-001.html" style="top:0px;left:390px;">
            <img width="390" height="150" src="http://www.ecejia.com/upload/ad/201209/11094426.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/156-001.html" style="top:150px;left:390px;">
            <img width="195" height="150" src="http://img03.taobaocdn.com/bao/uploaded/i3/T15d2qXXlrXXcRnJU2_043551.jpg_310x310.jpg" alt="">
        </a>        
        <a class="item" target="_blank" href="http://www.ecejia.com/product/122-1209072158.html" style="top:150px;left:585px;">
            <img width="195" height="150" src="http://img04.taobaocdn.com/bao/uploaded/i4/T1S0asXa8sXXcRc0w._111638.jpg_310x310.jpg" alt="">
        </a>
    </div>
    <div class="floor-bottom"></div>
</div>