<div class="floor">
    <div class="floor-top">
        <a href="#"><h2 class="floor-title"><span class="floor-name">1F</span>家居</h2></a>
        <ul class="floor-nav">
            <li><a href="#">卧室</a></li>
            <li><a href="#">客厅</a></li>
            <li><a href="#">餐厅</a></li>
            <li><a href="#">书房</a></li>
            <li><a href="#">儿童</a></li>
        </ul>
    </div>
    <div class="floor-middle">
        <ul class="floor-left floor-left-1">
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
            <li><a target="_blank" href="#" title="SK-II"></a></li>
        </ul>
        <div id="items" class="floor-right">
            <a class="item" target="_blank" href="#">
                <img width="195" height="150" src="http://img04.taobaocdn.com/imgextra/i4/90919986/T2TFuBXjhbXXXXXXXX_!!90919986.jpg" alt="东情西韵">
            </a>
            <a class="item" target="_blank" href="#">
                <img width="390" height="150" src="http://img02.taobaocdn.com/tps/i2/T1.ufHXbVdXXcaZvZe-390-150.png" alt="skii">
            </a>
            <a class="item" target="_blank" href="#">
                <img width="195" height="150" src="http://img01.taobaocdn.com/tps/i1/T1.3PBXidmXXc2tkZK-195-150.png" alt="美容馆男士护肤">
            </a>
            <a class="item" target="_blank" href="#">
                <img width="195" height="300" src="http://img01.taobaocdn.com/tps/i1/T1ZO2GXhBhXXXoDBZK-195-300.png" alt="首饰套件">
            </a>
            <a class="item" target="_blank" href="#">
                <img width="195" height="150" src="http://img03.taobaocdn.com/tps/i3/T1VPjDXXFfXXc2tkZK-195-150.png" alt="腕表">
            </a>
            <a class="item" target="_blank" href="#">
                <img width="195" height="150" src="http://img02.taobaocdn.com/tps/i2/T1VZHDXd4iXXc2tkZK-195-150.png" alt="铂金">
            </a>
        </div>
    </div>
    <div class="floor-bottom"></div>
</div>