<div class="floor">
    <div class="floor-top">
        <div class="floor-top-bg">
            <a href="#"><h2 class="floor-title"><span class="floor-name">4F</span>家装主材</h2></a>
        </div>
    </div>
    <ul class="hot-categorys f4">
        <li><div><a href="#">实木床</a></div><div><a href="#">儿童床</a></div></li>
        <li><div><a href="#">布沙发</a></div><div><a href="#">贵妃椅</a></div></li>
        <li><div><a href="#">实木床1111</a></div><div><a href="#">儿童床</a></div></li>
        <li><div><a href="#">实木床</a></div><div><a href="#">儿童床</a></div></li>
        <li><div><a href="#">布沙发</a></div><div><a href="#">贵妃椅</a></div></li>
        <li><div><a href="#">实木床1111</a></div><div><a href="#">儿童床</a></div></li>
        <li><div><a href="#">实木床</a></div><div><a href="#">儿童床</a></div></li>
        <li><div><a href="#">布沙发</a></div><div><a href="#">贵妃椅</a></div></li>
        <li><div><a href="#">实木床1111</a></div><div><a href="#">儿童床</a></div></li>
        <li><div></div><div></div></li>
    </ul>
    <div id="items" class="floor-middle-r">
        <a class="item" target="_blank" width="195" height="150" href="http://www.tmall.com/go/act/sale/dongqingxiyun.php?spm=3.1000473.246617.33" style="top:0px;left:0px;">
            <img width="195" height="150" src="http://img04.taobaocdn.com/imgextra/i4/90919986/T2TFuBXjhbXXXXXXXX_!!90919986.jpg" alt="东情西韵">
        </a>
        <a class="item" target="_blank" href="http://skii.tmall.com/?spm=3.1000473.246617.34" style="top:0px;left:195px;">
            <img width="390" height="150" src="http://img02.taobaocdn.com/tps/i2/T1.ufHXbVdXXcaZvZe-390-150.png" alt="skii">
        </a>
        <a class="item" target="_blank" href="http://www.tmall.com/go/act/tmall/mzdysy.php?spm=3.1000473.246617.35" style="top:150px;left:0px;">
            <img width="195" height="150" src="http://img02.taobaocdn.com/tps/i2/T1wWfJXoJXXXc2tkZK-195-150.png" alt="美妆大赛">
        </a>
        <a class="item" target="_blank" href="http://list.tmall.com/search_product.htm?spm=3.1000473.246617.36&amp;q=%CC%D7%D7%B0&amp;area_code=330100&amp;sort=s&amp;style=g&amp;vmarket=0&amp;active=1&amp;cat=50026461" style="top:0px;left:585px;">
            <img width="185" height="300" src="http://img01.taobaocdn.com/tps/i1/T1ZO2GXhBhXXXoDBZK-195-300.png" alt="首饰套件">
        </a>
        <a class="item" target="_blank" href="http://list.tmall.com/search_product.htm?spm=3.1000473.246617.37&amp;active=1&amp;from=sn_1_prop&amp;area_code=330100&amp;search_condition=16&amp;vmarket=0&amp;style=g&amp;sort=s&amp;start_price=100&amp;prop=34343:112571&amp;n=60&amp;s=0&amp;cat=50108176#J_crumbs" style="top:150px;left:195px;" >
            <img width="195" height="150" src="http://img03.taobaocdn.com/tps/i3/T1VPjDXXFfXXc2tkZK-195-150.png" alt="腕表">
        </a>
        <a class="item" target="_blank" href="http://list.tmall.com/search_product.htm?spm=3.1000473.246617.38&amp;active=1&amp;from=sn_1_cat&amp;area_code=330100&amp;navlog=5&amp;nav=spu-cat&amp;search_condition=16&amp;vmarket=0&amp;style=g&amp;sort=s&amp;n=48&amp;s=0&amp;cat=50026478&amp;is=cate#J_crumbs" style="top:150px;left:390px;">
            <img width="195" height="150" src="http://img02.taobaocdn.com/tps/i2/T1VZHDXd4iXXc2tkZK-195-150.png" alt="铂金">
        </a>
    </div>
    <div class="floor-bottom"></div>
</div>