<div class="floor">
    <div class="floor-top">
        <div class="floor-top-bar">
            <a class="floor-title-3" href="/channel/jiafang.html"></a>
        </div>
    </div>
    <ul class="hot-categorys f3">
        <li><div><a href="/list/211.html">四件套</a></div><div><a href="/list/212.html">枕头</a></div></li>
        <li><div><a href="/list/215.html">被子</a></div><div><a href="/list/221.html">地毯</a></div></li>
        <li><div><a href="/list/224.html">靠垫</a></div><div><a href="#">儿童床</a></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
    </ul>
    <div class="items floor-middle-r">
        <a class="item" target="_blank" href="http://www.ecejia.com/product/211-0002.html" style="top:0px;left:0px;">
            <img width="195" height="150" src="http://img04.taobaocdn.com/bao/uploaded/i4/T1qKJ5XddqXXXtp3La_090933.jpg_310x310.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/211-0004.html" style="top:0px;left:195px;">
            <img width="195" height="150" src="http://img03.taobaocdn.com/bao/uploaded/i3/T1VPzuXhFgXXXk6UU._113707.jpg_310x310.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/shop/1009.html" style="top:0px;left:390px;">
            <img width="390" height="150" src="http://www.ecejia.com/upload/ad/201209/12021804.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/211-003.html" style="top:150px;left:390px;">
            <img width="195" height="150" src="http://img02.taobaocdn.com/bao/uploaded/i2/T1lG6MXbleXXbcNyEY_030022.jpg_310x310.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/212-0001.html" style="top:150px;left:585px;">
            <img width="195" height="150" src="http://img01.taobaocdn.com/bao/uploaded/i1/T1_r5wXXVMXXXcmrjc_125818.jpg_310x310.jpg" alt="">
        </a>
        <a class="item hover" target="_blank" href="http://www.ecejia.com/shop/1009.html" style="top:150px;left:0px;">
            <img width="390" height="150" src="http://img01.taobaocdn.com/tps/i1/T1MArKXk0oXXcaZvZe-390-150.png" alt="">
        </a>
    </div>
    <div class="floor-bottom"></div>
</div>