<div class="floor">
    <div class="floor-top">
        <div class="floor-top-bar">
            <a class="floor-title-2" href="/channel/shipin.html"></a>
        </div>
    </div>
    <ul class="hot-categorys f2">
        <li><div><a href="/list/321.html">墙贴</a></div><div><a href="/list/331.html">摆件</a></div></li>
        <li><div><a href="/list/341.html">花瓶</a></div><div><a href="/list/343.thml">果盘</a></div></li>
        <li><div><a href="/list/344.html">装饰器皿</a></div><div><a href="/list/351.html">创意饰品</a></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
        <li><div></div><div></div></li>
    </ul>
    <div id="items" class="floor-middle-r">
        <a class="item" target="_blank" href="http://www.ecejia.com/shop/1010.html" style="top:0px;left:0px;">
            <img width="390" height="150" src="http://www.ecejia.com/upload/ad/201209/12035145.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/331-001.html" style="top:0px;left:390px;">
            <img width="195" height="300" src="http://www.ecejia.com/upload/ad/201209/12035853.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/311-001.html" style="top: 150px; left: 0px;">
            <img width="195" height="150" src="http://img01.taobaocdn.com/bao/uploaded/i1/T1TTGyXlVYXXaw1Zg2_043347.jpg_310x310.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/343.html" style="top:150px;left:195px;">
            <img width="195" height="150" src="http://img01.taobaocdn.com/bao/uploaded/i5/T1b1O9XoXXXXcSYu6b_123652.jpg_310x310.jpg" alt="">
        </a>
        <a class="item" target="_blank" href="http://www.ecejia.com/product/341-001.html" style="top:0px;left:585px;">
            <img width="195" height="300" src="http://www.ecejia.com/upload/ad/201209/12040058.jpg" alt="">
        </a>
    </div>
    <div class="floor-bottom"></div>
</div>