<div class="floor">
    <div class="floor-top">
        <div class="floor-top-bg">
            <a href="/channel/jiaju.html"><h2 class="floor-title"><span class="floor-name">1F</span>住宅家具</h2></a>
        </div>
    </div>
    <ul class="hot-categorys">
        <li><div><a target="_blank" href="/list/111.html">实木床</a></div><div><a target="_blank" href="/list/112.html">布艺床</a></div></li>
        <li><div><a target="_blank" href="/list/113.html">沙发床</a></div><div><a target="_blank" href="/list/114.html">儿童床</a></div></li>
        <li><div><a target="_blank" href="/list/121.html">布沙发</a></div><div><a target="_blank" href="/list/122.html">皮沙发</a></div></li>
        <li><div><a target="_blank" href="/list/124.html">实木沙发</a></div><div><a target="_blank" href="/list/125.html">懒人沙发</a></div></li>
        <li><div><a target="_blank" href="/list/126.html">贵妃椅</a></div><div><a target="_blank" href="/list/127.html">沙发床</a></div></li>
        <li><div><a target="_blank" href="/list/131.html">衣柜</a></div><div><a target="_blank" href="/list/133.html">电视柜</a></div></li>
        <li><div><a target="_blank" href="/list/134.html">床头柜</a></div><div><a target="_blank" href="/list/135.html">书柜</a></div></li>
        <li><div><a target="_blank" href="/list/155.html">书架</a></div><div><a target="_blank" href="/list/156.html">茶机</a></div></li>
        <li><div><a target="_blank" href="/list/158.html">书桌</a></div><div><a target="_blank" href="/list/157.html">餐桌</a></div></li>
        <li><div></div><div></div></li>
    </ul>
    <div id="items" class="floor-middle-r">
        <a class="item" target="_blank" href="#" >
            <img style="width:390px;height:300px;" src="http://img03.taobaocdn.com/bao/uploaded/i3/T19ZqsXhVyXXaiUWQ._111314.jpg_310x310.jpg">
        </a>
        <a class="item" target="_blank" href="#" style="top:0px;left:390px;">
            <img width="390" height="150" src="http://img02.taobaocdn.com/tps/i2/T15L2KXo0gXXcaZvZe-390-150.png" alt="家装团">
        </a>
        <a class="item" target="_blank" href="#" style="top:150px;left:390px;">
            <img width="195" height="150" src="http://img01.taobaocdn.com/tps/i1/T1nQzEXgXeXXc2tkZK-195-150.png" alt="建材">
        </a>        
        <a class="item" target="_blank" href="#" style="top:150px;left:585px;">
            <img width="195" height="150" src="http://img01.taobaocdn.com/tps/i1/T1TDPHXb4gXXc2tkZK-195-150.png" alt="居家新体验">
        </a>
    </div>
    <div class="floor-bottom"></div>
</div>