<?php echo $this->partial('index/_floor1.phtml'); ?>
<?php echo $this->partial('index/_floor2.phtml'); ?>
<?php echo $this->partial('index/_floor3.phtml'); ?>

<div style="height:90px;margin:10px 0;overflow:hidden;">
	<object width="980" height="90" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
	<param value="http://img6.jiameng.com/2012/06/u8ma8uz46fpf.swf" name="movie">
	<param name="wmode" value="transparent">
	<param value="high" name="quality">
	<embed wmode="transparent" width="980" height="90" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://img6.jiameng.com/2012/06/u8ma8uz46fpf.swf"></object>
</div>

<?php echo $this->partial('index/_floor4.phtml'); ?>
<?php echo $this->partial('index/_floor5.phtml'); ?>
