<?php echo $this->partial('index/_floor1.phtml'); ?>
<?php echo $this->partial('index/_floor2.phtml'); ?>
<?php echo $this->partial('index/_floor3.phtml'); ?>

<div class="layout f-poster"><a href="#" target="_blank">
	<img border="0" src="http://i.mmcdn.cn/simba/img/T1pFHGXixlXXb1upjX.jpg?noq=y" width="970px" height="90px"></a>
</div>

<?php echo $this->partial('index/_floor4.phtml'); ?>
<?php echo $this->partial('index/_floor5.phtml'); ?>
