<div class="nav-sub-box" style="margin-left:-100px;">
    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
            <dt>床上用品</dt>
            <dd><a target="_blank" href="/list/211.html">四件套</a></dd>
            <dd><a target="_blank" href="/list/212.html">枕头</a></dd>
            <dd><a target="_blank" href="/list/213.html">床单</a></dd>
            <dd><a target="_blank" href="/list/214.html">被套</a></dd>
            <dd><a target="_blank" href="/list/215.html">被子</a></dd>
        </dl>
        <dl class="nav-sub-detail-item">
            <dt>家居布艺</dt>
            <dd><a target="_blank" href="/list/221.html">地毯</a></dd>
            <dd><a target="_blank" href="/list/222.html">地垫</a></dd>
            <dd><a target="_blank" href="/list/223.html">挂毯</a></dd>
            <dd><a target="_blank" href="/list/224.html">靠垫</a></dd>
            <dd><a target="_blank" href="/list/225.html">休闲毯</a></dd>
            <dd><a target="_blank" href="/list/226.html">坐垫</a></dd>
        </dl>
    </div>
    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
            <dt>窗帘/帘类</dt>
            <dd><a target="_blank" href="/list/241.html">成品窗帘</a></dd>
            <dd><a target="_blank" href="/list/242.html">定制窗帘</a></dd>
            <dd><a target="_blank" href="/list/243.html">门帘</a></dd>
            <dd><a target="_blank" href="/list/244.html">轨道</a></dd>
            <dd><a target="_blank" href="/list/245.html">其他帘类</a></dd>
            <dd><a target="_blank" href="/list/246.html">窗帘配件</a></dd>
        </dl>
        <dl class="nav-sub-detail-item">
            <dt>布艺罩巾</dt>
            <dd><a target="_blank" href="/list/251.html">沙发巾/沙发套</a></dd>
            <dd><a target="_blank" href="/list/252.html">家电罩</a></dd>
            <dd><a target="_blank" href="/list/253.html">万能盖巾</a></dd>
            <dd><a target="_blank" href="/list/254.html">其他罩类</a></dd>
            <dd><a target="_blank" href="/list/255.html">毛巾</a></dd>
            <dd><a target="_blank" href="/list/256.html">浴巾</a></dd>
            <dd><a target="_blank" href="/list/257.html">拖鞋</a></dd>
        </dl>
    </div>
</div>