<div class="nav-sub-box" style="margin-left:-150px;">
    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
			<dt>厨卫用品</dt>
			<dd><a target="_blank" href="/list/411.html">冲水器</a></dd>
			<dd><a target="_blank" href="/list/412.html">淋浴花洒</a></dd>
			<dd><a target="_blank" href="/list/413.html">浴巾架</a></dd>
			<dd><a target="_blank" href="/list/414.html">浴缸</a></dd>
			<dd><a target="_blank" href="/list/415.html">智能便盖</a></dd>
			<dd><a target="_blank" href="/list/416.html">淋浴房</a></dd>
			<dd><a target="_blank" href="/list/417.html">角阀</a></dd>
			<dd><a target="_blank" href="/list/418.html">地漏</a></dd>
			<dd><a target="_blank" href="/list/419.html">台上盆</a></dd>
        </dl>
        <dl class="nav-sub-detail-item">
			<dt>灯饰照明</dt>
			<dd><a target="_blank" href="/list/421.html">顶灯</a></dd>
			<dd><a target="_blank" href="/list/422.html">壁灯</a></dd>
			<dd><a target="_blank" href="/list/423.html">落地灯</a></dd>
			<dd><a target="_blank" href="/list/424.html">镜前灯</a></dd>
			<dd><a target="_blank" href="/list/425.html">小夜灯</a></dd>
			<dd><a target="_blank" href="/list/426.html">新奇特灯具</a></dd>
			<dd><a target="_blank" href="/list/427.html">LED灯</a></dd>
			<dd><a target="_blank" href="/list/428.html">荧光灯</a></dd>
			<dd><a target="_blank" href="/list/429.html">白炽灯</a></dd>
        </dl>
    </div>
    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
			<dt>地板瓷砖</dt>
			<dd><a target="_blank" href="/list/431.html">PVC地板</a></dd>
			<dd><a target="_blank" href="/list/432.html">强化地板</a></dd>
			<dd><a target="_blank" href="/list/433.html">实木地板</a></dd>
			<dd><a target="_blank" href="/list/434.html">实木复合地板</a></dd>
			<dd><a target="_blank" href="/list/435.html">釉面砖</a></dd>
			<dd><a target="_blank" href="/list/436.html">马赛克</a></dd>
			<dd><a target="_blank" href="/list/437.html">文化石</a></dd>
        </dl>
        <dl class="nav-sub-detail-item">
			<dt>热水器/浴霸</dt>
			<dd><a target="_blank" href="/list/441.html">电热水器</a></dd>
			<dd><a target="_blank" href="/list/442.html">燃气热水器</a></dd>
			<dd><a target="_blank" href="/list/443.html">太阳能热水器</a></dd>
			<dd><a target="_blank" href="/list/444.html">集成吊顶</a></dd>
			<dd><a target="_blank" href="/list/445.html">多功能浴霸</a></dd>
			<dd><a target="_blank" href="/list/446.html">灯暖式浴霸</a></dd>
        </dl>
    </div>
    <!-- <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
			<dt>五金电子</dt>
			<dd><a target="_blank" href="/list/451.html">门锁</a></dd>
			<dd><a target="_blank" href="/list/452.html">拉手</a></dd>
			<dd><a target="_blank" href="/list/453.html">手动工具</a></dd>
			<dd><a target="_blank" href="/list/454.html">电动工具</a></dd>
			<dd><a target="_blank" href="/list/455.html">仪器仪表</a></dd>
			<dd><a target="_blank" href="/list/456.html">开关</a></dd>
			<dd><a target="_blank" href="/list/457.html">插座</a></dd>
			<dd><a target="_blank" href="/list/458.html">监控</a></dd>
        </dl>
    </div> -->
</div>