<div class="nav-sub-box" style="margin-left:-80px;">
    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
            <dt>床类</dt>
            <dd><a target="_blank" href="/list/111.html" >实木床</a></dd>
            <dd><a target="_blank" href="/list/112.html" >布艺床</a></dd>
            <dd><a target="_blank" href="/list/113.html" >沙发床</a></dd>
            <dd><a target="_blank" href="/list/114.html" >儿童床</a></dd>
            <dd><a target="_blank" href="/list/115.html" >板式床</a></dd>
            <dd><a target="_blank" href="/list/116.html" >高低床</a></dd>
            <dd><a target="_blank" href="/list/117.html" >铁艺床</a></dd>
        </dl>
        <dl class="nav-sub-detail-item">
            <dt>沙发</dt>
            <dd><a target="_blank" href="/list/121.html" >布沙发</a></dd>
            <dd><a target="_blank" href="/list/122.html" >皮沙发</a></dd>
            <dd><a target="_blank" href="/list/123.html" >藤沙发</a></dd>
            <dd><a target="_blank" href="/list/124.html" >实木沙发</a></dd>
            <dd><a target="_blank" href="/list/125.html" >懒人沙发</a></dd>
            <dd><a target="_blank" href="/list/126.html" >贵妃椅</a></dd>
            <dd><a target="_blank" href="/list/127.html" >沙发床</a></dd>
            <dd><a target="_blank" href="/list/128.html" >充气沙发</a></dd>
        </dl>
    </div>
    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
            <dt>柜子</dt>
            <dd><a target="_blank" href="/list/131.html" >衣柜</a></dd>
            <dd><a target="_blank" href="/list/132.html" >简易衣柜</a></dd>
            <dd><a target="_blank" href="/list/133.html" >电视柜</a></dd>
            <dd><a target="_blank" href="/list/134.html" >床头柜</a></dd>
            <dd><a target="_blank" href="/list/135.html" >书柜</a></dd>
            <dd><a target="_blank" href="/list/136.html" >鞋柜</a></dd>
            <dd><a target="_blank" href="/list/137.html" >餐边柜</a></dd>
            <dd><a target="_blank" href="/list/138.html" >门厅柜</a></dd>
        </dl>
        <dl class="nav-sub-detail-item">
            <dt>椅/凳/榻</dt>
            <dd><a target="_blank" href="/list/141.html" >餐椅</a></dd>
            <dd><a target="_blank" href="/list/142.html" >电脑椅</a></dd>
            <dd><a target="_blank" href="/list/143.html" >换鞋凳</a></dd>
            <dd><a target="_blank" href="/list/144.html" >摇椅</a></dd>
        </dl>
    </div>

    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
            <dt>架类/桌子</dt>
            <dd><a target="_blank" href="/list/150.html" >梳妆台</a></dd>
            <dd><a target="_blank" href="/list/151.html" >置物架</a></dd>
            <dd><a target="_blank" href="/list/152.html" >衣帽架</a></dd>
            <dd><a target="_blank" href="/list/153.html" >鞋架</a></dd>
            <dd><a target="_blank" href="/list/154.html" >格架</a></dd>
            <dd><a target="_blank" href="/list/155.html" >书架</a></dd>
            <dd><a target="_blank" href="/list/156.html" >茶几</a></dd>
            <dd><a target="_blank" href="/list/157.html" >餐桌</a></dd>
            <dd><a target="_blank" href="/list/158.html" >书桌</a></dd>
            <dd><a target="_blank" href="/list/15A.html" >儿童学习桌</a></dd>
            <dd><a target="_blank" href="/list/15B.html" >茶几/几类</a></dd>
        </dl>
    </div>
</div>