<div class="nav-sub-box" style="margin-left:-200px;">
    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
			<dt>家用五金</dt>
			<dd><a target="_blank" href="/list/511.html">锁具</a></dd>
			<dd><a target="_blank" href="/list/512.html">家具五金</a></dd>
			<dd><a target="_blank" href="/list/513.html">拉手</a></dd>
			<dd><a target="_blank" href="/list/514.html">合页</a></dd>
			<dd><a target="_blank" href="/list/515.html">门吸</a></dd>
			<dd><a target="_blank" href="/list/516.html">铰链</a></dd>
			<dd><a target="_blank" href="/list/517.html">缎带/扎带</a></dd>
        </dl>
        <dl class="nav-sub-detail-item">
			<dt>开关插座</dt>
			<dd><a target="_blank" href="/list/521.html">开关</a></dd>
			<dd><a target="_blank" href="/list/522.html">插座</a></dd>
			<dd><a target="_blank" href="/list/523.html">接线板/插头</a></dd>
			<dd><a target="_blank" href="/list/524.html">变压器</a></dd>
			<dd><a target="_blank" href="/list/525.html">太阳能电池</a></dd>
			<dd><a target="_blank" href="/list/526.html">电工配件</a></dd>
			<dd><a target="_blank" href="/list/527.html">LED设备</a></dd>
        </dl>
    </div>
    <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
			<dt>监控防盗</dt>
			<dd><a target="_blank" href="/list/531.html">成套监控系统</a></dd>
			<dd><a target="_blank" href="/list/532.html">监控摄像机</a></dd>
			<dd><a target="_blank" href="/list/533.html">监控器材/配件</a></dd>
			<dd><a target="_blank" href="/list/534.html">报警主机</a></dd>
        </dl>
        <dl class="nav-sub-detail-item">
			<dt>工具</dt>
			<dd><a target="_blank" href="/list/541.html">工具套装</a></dd>
			<dd><a target="_blank" href="/list/542.html">螺丝批</a></dd>
			<dd><a target="_blank" href="/list/543.html">电钻</a></dd>
			<dd><a target="_blank" href="/list/544.html">测量工具</a></dd>
			<dd><a target="_blank" href="/list/545.html">焊接喷涂</a></dd>
			<dd><a target="_blank" href="/list/546.html">夹持类</a></dd>
			<dd><a target="_blank" href="/list/547.html">手动工具</a></dd>
			<dd><a target="_blank" href="/list/548.html">电动工具</a></dd>
			<dd><a target="_blank" href="/list/549.html">气动工具</a></dd>
        </dl>
    </div>
    <!-- <div class="nav-sub-detail-box">
        <dl class="nav-sub-detail-item">
			<dt>其他</dt>
			<dd><a target="_blank" href="/list/551.html">万用表</a></dd>
			<dd><a target="_blank" href="/list/552.html">电子称</a></dd>
			<dd><a target="_blank" href="/list/553.html">阀门</a></dd>
			<dd><a target="_blank" href="/list/554.html">仪器仪表</a></dd>
			<dd><a target="_blank" href="/list/555.html">机械五金</a></dd>
			<dd><a target="_blank" href="/list/556.html">机电五金</a></dd>
		</dl>
	</div> -->
</div>